/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable

<% for (let collection of collections) { %>
export * from '<%= packageName %>/<%= path %>/<%= collection.normalizedName %>';<% } %>
<% for (let icon of icons) { %>
export * from './<%= icon.normalizedName %>';<% } %>