/*
 * Autogenerated by schematics
 */
import {<% for (let icon of icons) { %>
  SvIcon<%= classify(icon.normalizedName) %>,
  Icon<%= classify(icon.normalizedName) %>,<% } %>
} from '<%= packageName %>/<%= path %>';

export const ICON_META = [<% for (let icon of icons) { %>
  {
    svgSelector: 'svg[<%= prefix %>Icon<%= classify(normalizedName) %>]',
    svgClassName: 'SvgIcon<%= classify(icon.name) %>',
    svgComponent: SvgIcon<%= classify(icon.name) %>,
    wrapperSelector: 'sbb-icon-<%= dasherize(icon.normalizedName) %>',
    wrapperClassName: 'Icon<%= classify(icon.name) %>',
    wrapperComponent: Icon<%= classify(icon.name) %>,
    module: 'Icon<%= classify(icon.name) %>Module',
    import: '<%= packageName %>/<%= path %>/<%= icon.collections.join(`/`) %>'
  },<% } %>
];

export const ICON_CLASS_LIST = [<% for (let icon of icons) { %>
  SvgIcon<%= classify(icon.name) %>,
  Icon<%= classify(icon.name) %>,<% } %>
];